# Generated by Django 5.1.3 on 2025-10-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='timestamp',
        ),
    ]
